server {
    listen 80;
    server_name koraykural.com www.koraykural.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name koraykural.com www.koraykural.com;

    ssl_certificate /etc/letsencrypt/live/koraykural.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/koraykural.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/koraykural.com;
    index index.html;

    gzip_static on;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
